language: minimal

services: docker

before_install:
  - ./ci/scripts/install-dependencies.sh

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - ./ci/scripts/build.sh

deploy:
  provider: script
  script: ./ci/scripts/publish.sh
  on:
    branch: master