language: minimal

services: docker

before_install:
  - ./ci/scripts/install-dependencies.sh

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f ./ci/docker/build.docker-compose.yaml build --parallel

deploy:
  provider: script
  script: ./ci/scripts/publish.sh
  on:
    branch: master