language: minimal

services: docker

jobs:
  include:
    - stage: build
      before_install:
        - ./ci/scripts/install-dependencies.sh ci
      script: |+
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && \
        ./ci/scripts/build.sh
      deploy:
        provider: script
        on:
          branch: master
        script: ./ci/scripts/publish.sh
