version: "3"
services:
  reverse-proxy:
    image: y0n1/udagram-api-gateway 
    build:
      context: ./udagram-api-gateway
  backend-user:
    image: y0n1/udagram-rest-api-user
    build:
      context: ./udagram-rest-api-user
  backend-feed:
    image: y0n1/udagram-rest-api-feed
    build:
      context: ./udagram-rest-api-feed  
  front-end:
    image: y0n1/udagram-front-end
    build:
      context: ./udagram-front-end  
