apiVersion: v1
kind: Pod
metadata:
  name: udagram-feed-api
spec:
  containers:
    - image: y0n1/udagram-feed-api
      name: udagram-feed-api
      imagePullPolicy: Always
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "1024Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
  restartPolicy: Always
