apiVersion: v1
kind: Pod
metadata:
  name: udagram-reverse-proxy
spec:
  containers:
  - image: y0n1/udagram-reverse-proxy
    name: udagram-reverse-proxy
    imagePullPolicy: Always          
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "1024Mi"
        cpu: "500m"       
    ports:
    - containerPort: 8080
  restartPolicy: Always