apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-user-api
  name: udagram-user-api
spec:
  selector:
    matchLabels:
      service: udagram-user-api
  replicas: 1
  template:
    metadata:
      labels:
        service: udagram-user-api
    spec:
      containers:
        - image: y0n1/udagram-user-api
          name: udagram-user-api
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: URL
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: JWT_SECRET
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_USER
      restartPolicy: Always
