apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-web-client
  name: udagram-web-client
spec:
  selector:
    matchLabels:
      service: udagram-web-client
  replicas: 1
  template:
    metadata:
      labels:
        service: udagram-web-client
        api: external
    spec:
      containers:
        - image: y0n1/udagram-web-client
          name: udagram-web-client
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      restartPolicy: Always
