apiVersion: v1
kind: Pod
metadata:
  name: udagram-client
spec:
  containers:
    - image: y0n1/udagram-web-client
      name: udagram-web-client
      imagePullPolicy: Always
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "1024Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
  restartPolicy: Always
